### PR TITLE
Player keyboard and screenreader support

### PR DESCRIPTION
**Pull request by clpetersonucf**
So far:
- Added rudimentary keyboard support to the player. Use `tab` or `shift + tab` to navigate the list of tiles, `right arrow` to sort, `left arrow` to unsort, and `up` or `down` arrows to move sorted tiles up or down through the list. `Enter/return` to view the clue for a tile, if it exists. 
- Improved tab indexes and added auto-focus behavior to the sequence submission and "Are you sure?" dialogs.
- Improved focus and hover styles for certain buttons.
- Added some basic aria-live regions, including tile clues and notifications of certain user actions including tile sorting.

However, it's clear there's more work that needs to be done, particularly with keyboard navigation of the tile list and screen-reader navigation:
- Tabbing through the list of tiles remains unintuitive, because tab indexes are randomly shuffled when the tiles are placed. The tiles, when placed in the sorted list, do not change the tab order, which can be confusing.
- There are no aria-live updates to indicate a tile's position in the list, unless the ordering is modified with `up` or `down arrow`. 

Some ideas:
- Split the unsorted and sorted regions into two different list, within which the tiles can be selected via arrow keys or some other means.
- Tiles placed into the sorted section should have a coherent tab order based on their position in the list.
- Since arrow keys are likely to be used for tile navigation, we'll need to change the shortcuts for actually rearranging tiles in the sorted list.
- Confirm that the aria roles for the tile regions should be `list`, and if not, investigate a better role to assign to these.

### CODE REVIEW

**Comment by FrenjaminBanklin** [comment]
I'll be trying to finish this, focusing first on improving keyboard interactivity. Hopefully whatever has been done to address screen reader accessibility will still work once I'm done.

**Comment by FrenjaminBanklin** [comment]
New changes:


- Overhauled tab order. Every element on the page now has its own individual listener to handle Tab presses and move focus around depending on which element is currently in focus and what the state of the board is. More below.
- Keyboard instructions.
- A wraparound button that is invisible until it receives focus, both to help keyboard users navigate tiles more easily and to serve as a bookend so tab navigation still works properly.
- ARIA labels for the intro area and the newly added wraparound/keyboard instructions buttons.
- ARIA labels for the tiles will now indicate whether the tile is sorted or not.

Specifics of the new tab order implementation:
- When pressed on a tile, the next closest tile with a greater Y value (further from the top of the screen) will receive focus. If the `Shift` key is held down, the next closest tile with a lesser Y value will receive focus.
- When pressed on the wraparound or submit buttons, focus is allowed to leave the iframe as expected. If the `Shift` key is held down on the wraparound or submit buttons, focus will be moved to whichever tile is furthest down in the sequence. If no tiles are in the sequence, focus will be moved to whichever tile has the greatest Y value.
- When pressed on the keyboard instructions button, focus will be moved to whichever unsorted tile has the lowest Y value. If all tiles are sorted, focus will be moved to whichever tile is furthest up in the sequence. If the `Shift` key is held down, focus is allowed to leave the iframe as expected.

**Comment by clpetersonucf** [comment]
So far so good. Recommendations and things I've noticed so far:

- There's a lot of information to convey every time a new tile is focused. I might put "this tile has a clue" at the end of the label or description, because the information I care more about is a) the text on the tile and b) whether it's sequenced or unsequenced.
- I can still tab to the wraparound button when all tiles are sequenced, but selecting it doesn't do anything. It should probably be updated to say that there are no longer any unsequenced tiles.
- Sequencing all tiles should probably prompt an assertive live region update, but I didn't hear one.
- The results dialog doesn't report my performance upon submitting a sequence.
- The results dialog may be applying an `inert` attribute to the game board when it displays? I'm unable to interact with the widget once I dismiss it.

**Review by cayb0rg — COMMENTED** [review]
Phenomenal work. 

No issues hearing the ``_assistiveStatusUpdate`` calls. Just a few pretty minor things I noticed in addition to Corey's points:
* The “1”, “2”, “3” and “Score: 100%” in intro dialog should probably be made aria-hidden
* Both the ``correctMessage`` and ``allAttemptsMessage`` are visible to the screenreader in the results dialog
    * The ``resultsInner`` div should also probably be made aria-hidden or given an aria-label
* It's difficult to navigate to the number of guesses left using the arrow keys; attaching this information in an aria-label on the Submit Sequences button could be helpful

**Comment by FrenjaminBanklin** [comment]
Additional fixes/changes following review:

- Clicking the 'Try Again' button now properly removes the inert attribute from the game board.
- Shift-tabbing from the Submit button now correctly moves focus to the lowest sequenced tile.
- Tile labels now indicate the name first, then whether or not a tile is sequenced, and then whether or not a tile has a clue rather than name -> clue -> (un)sequenced.
- The 'Select First Unsorted Item' button is rendered inert when all tiles are sorted (using the keyboard), and has the inert attribute removed when any tile is unsorted (using the keyboard).
- Added `aria-hidden` attributes to several elements which are not necessary for screen readers.
- Added customized `aria-label`s to the confirmation dialog buttons.
- Adjusted the '# guesses' text to read '1 guess' when only one guess remains.

**Review by cayb0rg — COMMENTED** [review]
Looks good. Only one other thing I noticed - the ``submitScoreButton`` remains tabbable when all items are placed correctly.

**Comment by clpetersonucf** [comment]
Some additional thoughts after playtesting a bit:

- Knowing items are sequenced is useful but it might be useful to also know the index position of each sequenced tile when selected. That way it's easier to intuit where a tile is in the sequence relative to others.
- The "go back around" button could be improved by indicating how many tiles remain unsorted.

Otherwise, I didn't run into any additional show-stopping issues, it looks good.

**Comment by FrenjaminBanklin** [comment]
The wraparound button's `aria-label` will now indicate how many tiles have not been sorted yet.

When moving a tile in or out of the sequence or when changing a tile's order in the sequence, all tiles will have their `aria-label`s updated to indicate their current sort status and sequence position, if applicable.

**Comment by clpetersonucf** [comment]
I can't formally give approval since I was the original author of this PR, but the additions are solid. This looks ready to go.

**Review by FrenjaminBanklin — APPROVED** [review]
I did a lot of this myself so it feels a little weird approving it, but since it's been otherwise approved I'll call this ready to go.

**Pull request merged**
